# Generated by Django 6.0.3 on 2026-03-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(db_column='category_id', db_comment='카테고리 ID', primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='category_name', db_comment='카테고리 이름', max_length=20)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', db_comment='삭제 여부', default=False)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', db_comment='생성 일자')),
            ],
            options={
                'db_table': 'category',
                'db_table_comment': '카테고리 테이블',
            },
        ),
        migrations.CreateModel(
            name='PriceLog',
            fields=[
                ('log_id', models.BigAutoField(db_column='log_id', db_comment='로그 ID', primary_key=True, serialize=False)),
                ('store', models.IntegerField(db_column='store_id', db_comment='매장 ID', null=True)),
                ('owner', models.IntegerField(db_column='owner_id', db_comment='점주 ID', null=True)),
                ('product_dis_price', models.IntegerField(db_column='product_dis_price', db_comment='제품 할인 후 가격', null=True)),
                ('product_ori_price', models.IntegerField(db_column='product_ori_price', db_comment='제품 할인 전 가격', null=True)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', db_comment='생성 일자')),
            ],
            options={
                'db_table': 'price_log',
                'db_table_comment': '가격 로그 테이블',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(db_column='product_id', db_comment='제품 ID', primary_key=True, serialize=False)),
                ('store', models.IntegerField(db_column='store_id', db_comment='매장 ID', null=True)),
                ('category', models.IntegerField(db_column='category_id', db_comment='카테고리 ID', null=True)),
                ('product_name', models.CharField(db_column='product_name', db_comment='제품 이름', max_length=30)),
                ('product_desc', models.TextField(db_column='product_desc', db_comment='제품 설명', null=True)),
                ('product_stock', models.SmallIntegerField(db_column='product_stock', db_comment='제품 재고', null=True)),
                ('product_dis_price', models.IntegerField(db_column='product_dis_price', db_comment='제품 할인 후 가격', null=True)),
                ('product_ori_price', models.IntegerField(db_column='product_ori_price', db_comment='제품 할인 전 가격', null=True)),
                ('product_freshness', models.IntegerField(db_column='product_freshness', db_comment='제품 신선도', null=True)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', db_comment='삭제 여부', default=False)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', db_comment='생성 일자')),
            ],
            options={
                'db_table': 'product',
                'db_table_comment': '제품 정의 테이블',
            },
        ),
    ]
