# Generated by Django 6.0.3 on 2026-03-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(db_column='product_id', db_comment='제품 ID')),
                ('img_id', models.IntegerField(db_column='img_id', db_comment='이미지 ID')),
            ],
            options={
                'db_table': '제품 이미지 테이블',
            },
        ),
    ]
