# Generated by Django 6.0.3 on 2026-04-08 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        ('store', '0003_alter_storeworkingtime_working_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.BigAutoField(db_column='post_id', db_comment='제보 ID', primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, db_column='content', db_comment='제보 내용', null=True)),
                ('post_lon', models.DecimalField(db_column='post_long', db_comment='제보 위치 경도', decimal_places=7, max_digits=11)),
                ('post_lat', models.DecimalField(db_column='post_lat', db_comment='제보 위치 위도', decimal_places=7, max_digits=10)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', db_comment='삭제 여부', default=False)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', db_comment='제보 날짜')),
                ('img_id', models.ForeignKey(blank=True, db_column='post_img_id', db_comment='제보 이미지 ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='image.image')),
                ('store_id', models.ForeignKey(blank=True, db_column='store_id', db_comment='매장 ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store')),
                ('user_id', models.ForeignKey(db_column='user_id', db_comment='소비자 ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post',
                'db_table_comment': '제보 테이블',
                'ordering': ['-reg_dt'],
            },
        ),
    ]
