# Generated by Django 6.0.3 on 2026-04-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_name',
            field=models.CharField(db_column='post_name', db_comment='제보 이름', default='할인', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_lat',
            field=models.DecimalField(blank=True, db_column='post_lat', db_comment='제보 위치 위도', decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_lon',
            field=models.DecimalField(blank=True, db_column='post_long', db_comment='제보 위치 경도', decimal_places=7, max_digits=11, null=True),
        ),
    ]
