# Generated by Django 6.0.3 on 2026-04-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_post_name_alter_post_post_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_lon',
            new_name='post_long',
        ),
    ]
