# Generated by Django 4.2.29 on 2026-04-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_post_lon_post_post_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_long',
            field=models.DecimalField(blank=True, db_column='post_long', db_comment='제보 위치 경도', decimal_places=7, max_digits=10, null=True),
        ),
    ]
