# Generated by Django 4.2.29 on 2026-04-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_post_lat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_lat',
            field=models.DecimalField(blank=True, db_column='post_lat', db_comment='제보 위치 위도', decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_long',
            field=models.DecimalField(blank=True, db_column='post_long', db_comment='제보 위치 경도', decimal_places=7, max_digits=11, null=True),
        ),
    ]
