# Generated by Django 4.2.29 on 2026-05-18 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productimg_id_pricelog'),
        ('post', '0006_alter_post_post_lat_alter_post_post_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='product_id',
            field=models.ForeignKey(blank=True, db_column='product_id', db_comment='연관 상품 ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='product.product'),
        ),
    ]
