# Generated by Django 6.0.3 on 2026-03-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "user_id",
                    models.BigAutoField(
                        db_column="user_id",
                        db_comment="유저 ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "profile_img_id",
                    models.IntegerField(
                        db_column="profile_img_id",
                        db_comment="프로필 이미지 ID",
                        null=True,
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        db_column="user_name", db_comment="유저 이름", max_length=20
                    ),
                ),
                (
                    "user_phone",
                    models.CharField(
                        db_column="user_phone",
                        db_comment="유저 전화번호",
                        max_length=30,
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        db_column="user_email",
                        db_comment="유저 이메일",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        db_column="password",
                        db_comment="유저 비밀번호",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("U01", "customer"), ("U02", "owner")],
                        db_column="user_type",
                        db_comment="유저 타입",
                        max_length=10,
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(
                        db_column="provider_id",
                        db_comment="소셜 로그인 ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        db_column="platform",
                        db_comment="소셜 로그인 플랫폼",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "reg_dt",
                    models.DateTimeField(
                        auto_now_add=True, db_column="reg_dt", db_comment="생성 일자"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_comment="활성화 여부", default=True),
                ),
                (
                    "is_staff",
                    models.BooleanField(db_comment="스태프 여부", default=False),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "user",
                "db_table_comment": "유저 테이블",
            },
        ),
    ]
