# Generated by Django 6.0.3 on 2026-03-30 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('token_id', models.BigAutoField(db_column='token_id', db_comment='토큰 ID', primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_column='token', db_comment='재설정 토큰 (UUID)', default=uuid.uuid4, unique=True)),
                ('is_used', models.BooleanField(db_column='is_used', db_comment='사용 여부', default=False)),
                ('expired_at', models.DateTimeField(db_column='expired_at', db_comment='만료 일시')),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', db_comment='생성 일자')),
                ('user_id', models.ForeignKey(db_column='user_id', db_comment='유저 ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_token',
                'db_table_comment': '비밀번호 재설정 토큰 테이블',
            },
        ),
    ]
