# Generated by Django 6.0.3 on 2026-04-21 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationLog',
            fields=[
                ('log_id', models.BigAutoField(db_column='log_id', db_comment='위치 로그 ID', primary_key=True, serialize=False)),
                ('lat', models.FloatField(db_column='lat', db_comment='위치 위도')),
                ('long', models.FloatField(db_column='long', db_comment='위치 경도')),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', db_comment='저장 일시')),
                ('user_id', models.ForeignKey(db_column='user_id', db_comment='유저 ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'location_log',
                'db_table_comment': '사용자 위치 로그 테이블',
                'ordering': ['-reg_dt'],
            },
        ),
    ]
