# Generated by Django 4.2.29 on 2026-04-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_locationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationlog',
            name='long',
            field=models.FloatField(db_column='lon', db_comment='위치 경도'),
        ),
    ]
