# Generated by Django 4.2.29 on 2026-04-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_locationlog_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationlog',
            old_name='long',
            new_name='lon',
        ),
    ]
