# Generated by Django 6.0.3 on 2026-03-14 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "store_id",
                    models.BigAutoField(
                        db_column="store_id",
                        db_comment="매장 ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "store_name",
                    models.CharField(
                        db_column="store_name", db_comment="매장 이름", max_length=20
                    ),
                ),
                (
                    "store_address",
                    models.CharField(
                        db_column="store_address",
                        db_comment="매장 주소",
                        max_length=100,
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        db_column="is_closed",
                        db_comment="매장 마감 여부",
                        default=False,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_column="is_deleted", db_comment="삭제 여부", default=False
                    ),
                ),
                (
                    "reg_dt",
                    models.DateTimeField(
                        auto_now_add=True, db_column="reg_dt", db_comment="생성 일자"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        db_comment="유저 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "store",
                "db_table_comment": "매장 테이블",
            },
        ),
        migrations.CreateModel(
            name="OffDate",
            fields=[
                (
                    "closed_date_id",
                    models.BigAutoField(
                        db_column="closed_date_id",
                        db_comment="휴무 테이블 ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "off_dt",
                    models.DateField(
                        db_column="store_address", db_comment="휴무 예약일"
                    ),
                ),
                (
                    "off_desc",
                    models.TextField(
                        blank=True,
                        db_column="off_desc",
                        db_comment="휴무 사유",
                        null=True,
                    ),
                ),
                (
                    "reg_dt",
                    models.DateTimeField(
                        auto_now_add=True, db_column="reg_dt", db_comment="생성 일자"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        db_comment="유저 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store_id",
                    models.ForeignKey(
                        db_column="store_id",
                        db_comment="매장 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.store",
                    ),
                ),
            ],
            options={
                "db_table": "off_date",
                "db_table_comment": "매장 휴무 예약 테이블",
            },
        ),
        migrations.CreateModel(
            name="StoreWorkingTime",
            fields=[
                (
                    "working_time_id",
                    models.BigAutoField(
                        db_column="working_time_id",
                        db_comment="매장 운영시간 ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "working_day",
                    models.TextField(
                        db_column="store_address",
                        db_comment="매장 운영 요일",
                        max_length=10,
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        db_column="start_time", db_comment="매장 운영 시작 시간"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(db_column="end_time", db_comment="매장 마감 시간"),
                ),
                (
                    "store_id",
                    models.ForeignKey(
                        db_column="store_id",
                        db_comment="매장 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.store",
                    ),
                ),
            ],
            options={
                "db_table": "store_working_time",
                "db_table_comment": "매장 운영시간 테이블",
            },
        ),
    ]
