# Generated by Django 6.0.3 on 2026-03-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_lat',
            field=models.FloatField(db_column='store_lat', db_comment='매장 위도', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_long',
            field=models.DecimalField(db_column='store_long', db_comment='매장 경도', decimal_places=6, max_digits=9, null=True),
        ),
    ]
