# Generated by Django 6.0.3 on 2026-04-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_store_lat_store_store_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeworkingtime',
            name='working_day',
            field=models.TextField(db_column='working_day', db_comment='매장 운영 요일', max_length=10),
        ),
    ]
