# Generated by Django 6.0.3 on 2026-04-10 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_storeworkingtime_working_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', db_comment='생성 일자')),
                ('store_id', models.ForeignKey(db_column='store_id', db_comment='매장 ID', on_delete=django.db.models.deletion.CASCADE, to='store.store')),
                ('user_id', models.ForeignKey(db_column='user_id', db_comment='소비자 ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite',
                'db_table_comment': '즐겨찾기 테이블',
                'unique_together': {('user_id', 'store_id')},
            },
        ),
    ]
