# Generated by Django 6.0.3 on 2026-04-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_storeworkingtime_working_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_desc',
            field=models.TextField(db_column='store_desc', db_comment='매장 설명', null=True),
        ),
    ]
