# Generated by Django 6.0.3 on 2026-04-14 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('store', '0003_alter_storeworkingtime_working_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_img_id',
            field=models.ForeignKey(blank=True, db_column='store_img_id', db_comment='매장 이미지 ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='image.image'),
        ),
    ]
