# Generated by Django 6.0.3 on 2026-04-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_favorite'),
        ('store', '0004_store_store_desc'),
    ]

    operations = [
    ]
