# Generated by Django 4.2.29 on 2026-04-26 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_favorite_id'),
        ('store', '0005_merge_0004_favorite_0004_store_store_desc'),
    ]

    operations = [
    ]
