# Generated by Django 4.2.29 on 2026-04-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_merge_20260427_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_lat',
            field=models.DecimalField(db_column='store_lat', db_comment='매장 위도', decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_long',
            field=models.DecimalField(db_column='store_long', db_comment='매장 경도', decimal_places=7, max_digits=10, null=True),
        ),
    ]
