# Generated by Django 4.2.29 on 2026-04-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_store_store_lat_alter_store_store_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_long',
            field=models.DecimalField(db_column='store_long', db_comment='매장 경도', decimal_places=7, max_digits=11, null=True),
        ),
    ]
