# Generated by Django 4.2.29 on 2026-05-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_store_store_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeworkingtime',
            name='end_day_offset',
            field=models.SmallIntegerField(db_column='end_day_offset', db_comment='종료 요일 오프셋 (0=당일, 1=익일)', default=0),
        ),
    ]
