# Generated by Django 4.2.29 on 2026-06-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_add_auto_soldout_periodic_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offdate',
            name='off_dt',
            field=models.DateField(db_column='off_dt', db_comment='휴무 예약일'),
        ),
    ]
