# Generated by Django 6.0.3 on 2026-03-14 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "img_id",
                    models.BigAutoField(
                        db_column="img_id",
                        db_comment="이미지 ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "img_name",
                    models.CharField(
                        db_column="img_name", db_comment="이미지 이름", max_length=200
                    ),
                ),
                (
                    "img_url",
                    models.CharField(
                        db_column="img_url", db_comment="이미지 URL", max_length=255
                    ),
                ),
                (
                    "img_path",
                    models.CharField(
                        db_column="img_path", db_comment="이미지 경로", max_length=300
                    ),
                ),
                (
                    "img_uuid_name",
                    models.CharField(
                        db_column="img_uuid_name",
                        db_comment="UUID 이름",
                        max_length=255,
                    ),
                ),
                (
                    "reg_dt",
                    models.DateTimeField(
                        auto_now_add=True, db_column="reg_dt", db_comment="생성 일자"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        db_comment="업로드 유저",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "image",
                "db_table_comment": "이미지 테이블",
            },
        ),
    ]
