# Generated by Django 4.2.29 on 2026-04-12 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notification_id",
                    models.BigAutoField(
                        db_column="notification_id",
                        db_comment="알림 ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("N01", "주문 접수"),
                            ("N02", "주문 처리 완료"),
                            ("N03", "주문 취소"),
                            ("N04", "즐겨찾기 매장 신규 상품"),
                        ],
                        db_column="notification_type",
                        db_comment="알림 타입",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_column="is_active",
                        db_comment="알림 수신 여부 (토글)",
                        default=True,
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        db_comment="유저 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification",
                "db_table_comment": "알림 테이블",
                "unique_together": {("user_id", "notification_type")},
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "log_id",
                    models.BigAutoField(
                        db_column="log_id",
                        db_comment="알림 로그 ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_id",
                    models.BigIntegerField(
                        db_column="target_id",
                        db_comment="대상 ID (주문번호, 매장ID 등)",
                        null=True,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("ORDER", "주문"),
                            ("STORE", "매장"),
                            ("PRODUCT", "상품"),
                        ],
                        db_column="target_type",
                        db_comment="대상 타입",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_column="is_read", db_comment="읽음 여부", default=False
                    ),
                ),
                (
                    "reg_dt",
                    models.DateTimeField(
                        auto_now_add=True, db_column="reg_dt", db_comment="생성 일시"
                    ),
                ),
                (
                    "notification_id",
                    models.ForeignKey(
                        db_column="notification_id",
                        db_comment="알림 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="notification.notification",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        db_comment="수신 유저 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_log",
                "db_table_comment": "알림 로그",
                "ordering": ["-reg_dt"],
            },
        ),
    ]
