# Generated by Django 4.2.29 on 2026-04-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('N01', '주문 접수'), ('N02', '주문 처리 완료'), ('N03', '주문 취소'), ('N04', '즐겨찾기 매장 신규 상품'), ('N05', '주문 수락'), ('N06', '특가 상품 알림')], db_column='notification_type', db_comment='알림 타입', max_length=10),
        ),
    ]
