# Generated by Django 6.0.3 on 2026-04-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('S01', '주문 접수'), ('S02', '처리 중'), ('S03', '처리 완료'), ('S04', '주문 취소')], db_column='order_status', db_comment='주문 상태', max_length=10),
        ),
    ]
