# Generated by Django 4.2.29 on 2026-04-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprodlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
