# Generated by Django 6.0.3 on 2026-03-14 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GroupCode",
            fields=[
                (
                    "group_code",
                    models.TextField(
                        db_column="group_code",
                        db_comment="그룹코드",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "group_code_nm",
                    models.TextField(
                        db_column="group_code_nm",
                        db_comment="그룹코드 이름",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "reg_dt",
                    models.DateTimeField(
                        auto_now_add=True, db_column="reg_dt", db_comment="등록 일시"
                    ),
                ),
            ],
            options={
                "db_table": "group_code",
                "db_table_comment": "그룹코드",
            },
        ),
        migrations.CreateModel(
            name="CommonCode",
            fields=[
                (
                    "common_code",
                    models.TextField(
                        db_column="group_code",
                        db_comment="공통코드",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code_nm",
                    models.TextField(
                        db_column="code_nm", db_comment="공통코드 이름", max_length=50
                    ),
                ),
                (
                    "reg_dt",
                    models.DateTimeField(
                        auto_now_add=True, db_column="reg_dt", db_comment="등록 일시"
                    ),
                ),
                (
                    "group_code_nm",
                    models.ForeignKey(
                        db_column="group_code_nm",
                        db_comment="그룹코드 이름",
                        max_length=10,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.groupcode",
                    ),
                ),
            ],
            options={
                "db_table": "common_code",
                "db_table_comment": "공통코드",
            },
        ),
    ]
