# Generated by Django 6.0.3 on 2026-03-15 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(db_column='category_id', db_comment='카테고리 ID', primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='category_name', db_comment='카테고리 이름', max_length=20)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', db_comment='삭제 여부', default=False)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', db_comment='생성 일자')),
            ],
            options={
                'db_table': 'category',
                'db_table_comment': '카테고리 테이블',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(db_column='product_id', db_comment='제품 ID', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='product_name', db_comment='제품 이름', max_length=30)),
                ('product_desc', models.TextField(db_column='product_desc', db_comment='제품 설명', null=True)),
                ('product_count', models.SmallIntegerField(db_column='product_count', db_comment='제품 재고', null=True)),
                ('product_dis_price', models.IntegerField(db_column='product_dis_price', db_comment='제품 할인 후 가격', null=True)),
                ('product_ori_price', models.IntegerField(db_column='product_ori_price', db_comment='제품 할인 전 가격', null=True)),
                ('product_freshness', models.IntegerField(db_column='product_freshness', db_comment='제품 신선도', null=True)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', db_comment='삭제 여부', default=False)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', db_comment='생성 일자')),
                ('category_id', models.ForeignKey(db_column='category_id', db_comment='카테고리 ID', on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('store_id', models.ForeignKey(db_column='store_id', db_comment='매장 ID', on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'db_table': 'product',
                'db_table_comment': '제품 정의 테이블',
            },
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.ForeignKey(db_column='img_id', db_comment='카테고리 ID', on_delete=django.db.models.deletion.CASCADE, to='image.image')),
                ('product_id', models.ForeignKey(db_column='product_id', db_comment='매장 ID', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': '제품 이미지 테이블',
            },
        ),
    ]
