# Generated by Django 6.0.3 on 2026-03-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_freshness',
        ),
    ]
