# Generated by Django 4.2.29 on 2026-04-26 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_favorite_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_remove_product_product_freshness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimg',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PriceLog',
            fields=[
                ('log_id', models.BigAutoField(db_column='log_id', db_comment='로그 ID', primary_key=True, serialize=False)),
                ('product_dis_price', models.IntegerField(db_column='product_dis_price', db_comment='제품 할인 후 가격', null=True)),
                ('product_ori_price', models.IntegerField(db_column='product_ori_price', db_comment='제품 할인 전 가격', null=True)),
                ('discount_rate', models.IntegerField(db_column='discount_rate', db_comment='제품 할인율 (%)', null=True)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', db_comment='생성 일자')),
                ('owner_id', models.ForeignKey(db_column='owner_id', db_comment='점주 ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(db_column='product_id', db_comment='제품 ID', on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='product.product')),
                ('store_id', models.ForeignKey(db_column='store_id', db_comment='매장 ID', on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'db_table': 'price_log',
                'db_table_comment': '가격 로그 테이블',
                'ordering': ['-reg_dt'],
            },
        ),
    ]
