# Generated by Django 6.0.3 on 2026-03-15 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(db_column='order_id', db_comment='주문 번호', primary_key=True, serialize=False)),
                ('order_status', models.CharField(choices=[('CREATED', '생성됨'), ('PAID', '결제완료'), ('PICKED_UP', '픽업완료'), ('FAILED', '결제/주문실패'), ('CANCELLED', '주문취소')], db_column='order_status', db_comment='주문 상태', max_length=10)),
                ('pickup_dt', models.DateTimeField(db_column='pickup_dt', db_comment='픽업 일시', null=True)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', db_comment='주문 일시')),
                ('store_id', models.ForeignKey(db_column='store_id', db_comment='매장 ID', on_delete=django.db.models.deletion.CASCADE, to='store.store')),
                ('user_id', models.ForeignKey(db_column='user_id', db_comment='소비자 ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
                'db_table_comment': '주문 테이블 정의',
            },
        ),
        migrations.CreateModel(
            name='OrderProdList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_prod_count', models.SmallIntegerField(db_column='order_prod_count', db_comment='주문한 제품 개수')),
                ('product_dis_price', models.IntegerField(db_column='product_dis_price', db_comment='제품 할인 후 가격')),
                ('product_ori_price', models.IntegerField(db_column='product_ori_price', db_comment='제품 할인 전 가격')),
                ('order_id', models.ForeignKey(db_column='order_id', db_comment='주문 번호', on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product_id', models.ForeignKey(db_column='product_id', db_comment='제품 ID', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'order_item',
                'db_table_comment': '주문한 제품 상세 테이블',
            },
        ),
    ]
